//PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const POST_PRODUCTS = 'POST_PRODUCTS';
export const POST_PRODUCTS_REQUEST = 'POST_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';

//SCANS
export const GET_SCANS = 'GET_SCANS';
export const GET_SCANS_REQUEST = 'GET_SCANS_REQUEST';
export const POST_SCANS = 'POST_SCANS';
export const POST_SCANS_REQUEST = 'POST_SCANS_REQUEST';
export const SEARCH_SCANS = 'SEARCH_SCANS';
export const SEARCH_SCANS_REQUEST = 'SEARCH_SCANS_REQUEST';
export const SET_NEW_SCAN = 'SET_NEW_SCAN'
export const SET_SCANNED_BARCODE = 'SET_SCANNED_BARCODE';


export const GET_NEAR_PLACES = 'GET_NEAR_PLACES'
export const GET_NEAR_PLACES_REQUEST = 'GET_NEAR_PLACES_REQUEST'



export const SET_NEW_PRODUCT = "SET_NEW_PRODUCT";

export const SHOW_COMMON_ALERT = "SHOW_COMMON_ALERT";
export const HIDE_COMMON_ALERT = "HIDE_COMMON_ALERT";


//tubu  chain//
//Contracts
export const GET_CONTRACTS = 'GET_CONTRACTS ';
export const GET_CONTRACTS_REQUEST = 'GET_CONTRACTS_REQUEST';
export const GET_CONTRACTS_COUNT = 'GET_CONTRACTS_COUNT ';
export const SET_CONTRACTS_COUNT = "SET_CONTRACTS_COUNT ";
export const GET_CONTRACTS_COUNT_REQUEST = 'GET_CONTRACTS_COUNT_REQUEST';
export const SEARCH_CONTRACTS = "SEARCH_CONTRACTS ";
export const SEARCH_CONTRACTS_REQUEST = "SEARCH_CONTRACTS_REQUEST ";


//Transactions
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS ';
export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST ';
export const GET_TRANSACTIONS_COUNT = "GET_TRANSACTIONS_COUNT ";
export const SET_TRANSACTIONS_COUNT = "SET_TRANSACTIONS_COUNT ";
export const GET_TRANSACTIONS_COUNT_REQUEST = "GET_TRANSACTIONS_COUNT_REQUEST ";
export const SEARCH_TRANSACTIONS = "SEARCH_TRANSACTIONS ";
export const SEARCH_TRANSACTIONS_REQUEST = "SEARCH_TRANSACTIONS_REQUEST ";

//Blocks
export const GET_BLOCKS = "GET_BLOCKS ";
export const GET_BLOCKS_REQUEST = "GET_BLOCKS_REQUEST ";
export const GET_BLOCKS_COUNT = "GET_BLOCKS_COUNT ";
export const SET_BLOCKS_COUNT = "SET_BLOCKS_COUNT ";
export const GET_BLOCKS_COUNT_REQUEST = "GET_BLOCKS_COUNT_REQUEST ";
export const GET_BLOCK_TRANSACTIONS = "GET_BLOCK_TRANSACTIONS ";
export const RESET_BLOCK_TRANSACTIONS = "RESET_BLOCK_TRANSACTIONS ";
export const GET_BLOCK_TRANSACTIONS_REQUEST = "GET_BLOCK_TRANSACTIONS_REQUEST ";
export const SEARCH_BLOCKS = "SEARCH_BLOCKS ";
export const SEARCH_BLOCKS_REQUEST = "SEARCH_BLOCKS_REQUEST ";

//Peers
export const GET_NODE_INFO = "GET_NODE_INFO";
export const GET_NODE_INFO_REQUEST = "GET_NODE_INFO_REQUEST ";
export const GET_PEERS = "GET_PEERS ";
export const GET_PEERS_REQUEST = "GET_PEERS_REQUEST ";

//Wallets
export const GET_WALLETS = "GET_WALLETS";
export const GET_WALLETS_REQUEST = "GET_WALLETS_REQUEST ";
export const CREATE_WALLET = "CREATE_WALLET ";
export const CREATE_WALLET_REQUEST = "CREATE_WALLET_REQUEST ";
